/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package com.sample 

import java.util.HashMap
import org.drools.compiler.*

global com.sample.X x
global com.sample.Yada yada

function void myFunc( Bar foo, Bing bada ) {
    
        System.out.println("hello world");
    
}


rule "my rule"
when
    Foo(  )  
    bar : Bar(  )  
    Foo( var1 : field1, field1 == "value1" && == (1==1) && == var1, eval(1==1) )  
    not( 
    Bar(  )   ) 
    exists( 
    Bar(  )   ) 
    
    (Yada(  )
     and
    Bar(  ))
    
    (Zaa(  )
     or
    Foo(  ))

    eval( 1==1 ) 
then

    end
