---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /unprotected:
    post:
      operationId: doOperation
      security:
        - client_id: [ ]
        - oauth: [ read, write ]
        - bearerAuth: [ ]
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MultiplicationOperation'
      responses:
        "200":
          description: OK
components:
  schemas:
    MultiplicationOperation:
      type: object
  securitySchemes:
    client_id:
      type: apiKey
      in: header
      name: X-Client-Id
      x-key-type: clientId
