#
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
#

swagger: '2.0'
info:
  title: myapp-iq9MzY
  version: 2.0.0
basePath: /iq9MzY
paths:
  /watsonorchestrate:
    post:
      tags:
        - myapp
      summary: Create a new instance of the model and persist it into the data source.
      operationId: myapp.create
      parameters:
        - name: data
          in: body
          #description: Model instance data
          required: false
          schema:
            #description: Model instance data
            $ref: '#/definitions/myapp'
      responses:
        '201':
          description: Request was successful
          schema:
            $ref: '#/definitions/myapp'
      deprecated: false
definitions:
  myapp:
    #description: ''
    properties:
      userid:
        type: string
    required:
      - userid
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  client_id:
    type: apiKey
    in: header
    name: X-Client-Id
    x-key-type: clientId
  basicAuth:
    type: basic
security:
  - client_id: [ ]
  - basicAuth: []
tags:
  - name: myapp
