---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /testArray:
    post: 
      operationId: testArray
      requestBody: 
        content:
          application/json:
            schema:
              type: array
              items: 
                type: number
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
