---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /:
    post:
      operationId: Do Operation
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SubtractionOperation'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  difference:
                    format: float
                    type: number
components:
  schemas:
    SubtractionOperation:
      type: object
      properties:
        leftElement:
          format: float
          type: number
        rightElement:
          format: float
          type: number