/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.jbpm.process.codegen;

import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.inject.Produces;
import jakarta.inject.Inject;

import org.eclipse.microprofile.config.Config;
import org.kogito.workitem.rest.RestWorkItemHandlerConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Producer for RestWorkItemHandlerConfig that reads configuration from application.properties.
 * This class is generated by the Kogito code generator.
 */
@ApplicationScoped
public class RestWorkItemHandlerConfigProducer {

    private static final Logger logger = LoggerFactory.getLogger(RestWorkItemHandlerConfigProducer.class);
    private static final String CONFIG_PREFIX = "kogito.processes.";

    @Inject
    Config config;

    @Produces
    @ApplicationScoped
    public RestWorkItemHandlerConfig restWorkItemHandlerConfig() {
        RestWorkItemHandlerConfig handlerConfig = new RestWorkItemHandlerConfig();
        
        logger.debug("Initializing RestWorkItemHandlerConfig from application properties");
        
        // Iterate through all configuration properties
        for (String propertyName : config.getPropertyNames()) {
            if (propertyName.startsWith(CONFIG_PREFIX)) {
                try {
                    String value = config.getValue(propertyName, String.class);
                    handlerConfig.parseAndRegister(propertyName, value);
                    logger.debug("Registered configuration: {} = {}", propertyName, value);
                } catch (Exception e) {
                    logger.warn("Failed to register configuration property: {}", propertyName, e);
                }
            }
        }
        
        logger.info("RestWorkItemHandlerConfig initialized with {} process configurations", 
                    handlerConfig.getAllProcessIds().size());
        
        return handlerConfig;
    }
}

