swagger: '2.0'
info:
  title: myapp-iq9MzY
  version: 2.0.0
basePath: /iq9MzY
paths:
  /watsonorchestrate:
    post:
      tags:
        - myapp
      summary: Create a new instance of the model and persist it into the data source.
      operationId: myapp.create
      parameters:
        - name: data
          in: body
          description: Model instance data
          required: false
          schema:
            description: Model instance data
            $ref: '#/definitions/myapp'
      responses:
        '201':
          description: Request was successful
          schema:
            $ref: '#/definitions/myapp'
      deprecated: false
definitions:
  myapp:
    description: ''
    properties:
      userid:
        type: string
    required:
      - userid
    additionalProperties: false
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
x-configuration:
  assembly:
    execute:
      - set-variable:
          actions:
            - set: message.headers.Authorization
              value: >-
                Basic
                dGhpc2lzYXRlc3QK
      - invoke:
          target-url: >-
            https://myapp.sso.com$(request.path)$(request.search)
          verb: keep
  cors:
    enabled: true
securityDefinitions:
  client_id:
    type: apiKey
    in: header
    name: X-Client-Id
    x-key-type: clientId
  oauth:
    type: oauth2
    flow: accessCode
    authorizationUrl: https://example.com/oauth/authorize
    tokenUrl: https://example.com/oauth/token
    scopes:
      read: Grants read access
      write: Grants write access
      admin: Grants read and write access to administrative information
security:
  - client_id: [ ]
  - oauth: [ read, write ]
tags:
  - name: myapp
