{
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "$handlerName$ instances started per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kie_process_instance_started_total{process_id=\"$handlerName$\"}[1d]))"
    }
   ]
  },
  {
   "title": "$handlerName$ instances running per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(kie_process_instance_running_total{process_id=\"$handlerName$\"}[1d]))"
    }
   ]
  },
  {
   "title": "$handlerName$ instances SLA violated per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(kie_process_instance_sla_violated_total{process_id=\"$handlerName$\"}[1d]))"
    }
   ]
  },
  {
   "title": "$handlerName$ instances completed per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(kie_process_instance_completed_total{process_id=\"$handlerName$\"}[1d]))"
    }
   ]
  }
 ]
}