{
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "$handlerName$ instances started",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(kie_process_instance_started_total{process_id='$handlerName$'})"
    }
   ]
  },
  {
   "title": "$handlerName$ running instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(kie_process_instance_running_total{process_id='$handlerName$'})"
    }
   ]
  },
  {
   "title": "$handlerName$ completed instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kie_process_instance_completed_total{process_id='$handlerName$'})"
    }
   ]
  },
  {
   "title": "$handlerName$ SLA violated instances",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "sum(kie_process_instance_sla_violated_total{process_id='$handlerName$'})"
    }
   ]
  },
  {
   "title": "$handlerName$ process execution time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kie_process_instance_duration_seconds_sum{process_id='$handlerName$'}[1m])/avg_over_time(kie_process_instance_duration_seconds_count{process_id='$handlerName$'}[1m])",
     "legendFormat": "{{process_id}}"
    }
   ]
  }
 ]
}