# Copyright IBM Corp. 2025.

quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.image-name=mirror.gcr.io/postgres:15.9-alpine3.20
# Disable container reuse to ensure a clean database on every test run
#quarkus.datasource.devservices.reuse=false

kogito.persistence.type=jdbc

quarkus.hibernate-orm.database.generation=none

kie.flyway.enabled=true

# Logging
quarkus.log.category."org.acme".level=INFO

# Transaction rollback test configuration
# Set to true to simulate external system failure in UserTaskEventListener
app.listener.fail-on-complete=true
