name: Upload to sonar

on:
  workflow_run:
    workflows: [Kogito Runtimes Build]
    types:
      - completed

jobs:
  sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Clean Disk Space
        uses: kiegroup/kogito-pipelines/.ci/actions/ubuntu-disk-space@main
      - name: Java and Maven Setup
        uses: kiegroup/kogito-pipelines/.ci/actions/maven@main
        with:
          java-version: 11
          maven-version: '3.8.6'
          cache-key-prefix: ubuntu-latest-11-maven3.8.6

      - name: Download jacoco reports
        uses: actions/github-script@v6
        with:
          script: |
            let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: context.payload.workflow_run.id,
            });
            let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
              return artifact.name == "report"
            })[0];
            let download = await github.rest.actions.downloadArtifact({
               owner: context.repo.owner,
               repo: context.repo.repo,
               artifact_id: matchArtifact.id,
               archive_format: 'zip',
            });
            let fs = require('fs');
            fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/report.zip`, Buffer.from(download.data));
      
      - name: Unzip files
        run: unzip report.zip

      - name: upload to sonar
        run: mvn validate -Pupload-to-sonar -e -nsu -fae -ntp
        env:
          SONAR_REPORT_DIR: report
          SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}

      